subcomponents:
  simple-service:
    namespace: services
    config:
      # gateway: tax-dev-esp.hrblock.net
      service:
        dns: tax-dev-esp.hrblock.net
        name: bc-service
        port: 80
      configMap:
        PORT: 80
      tiers:
        canary:
          image: "timfpark/bc-service:441"
          replicas: 1
          weight: 10
          port: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"

        stable:
          image: "timfpark/bc-service:440"
          replicas: 3
          weight: 90
          port: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
