name: "kube-prometheus"
type: static
path: "./manifests"
subcomponents:
  - name: "prometheus"
    # type: helm
    source: "https://github.com/coreos/kube-prometheus"
    method: "git"
    path: "jsonnet/kube-prometheus"
